---
- name: Update cache
  become: yes
  apt: update_cache=true

- name: Install system packages
  become: yes
  apt: name="{{ item }}" state=present
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - ruby
    - tmux
    - git

- name: Install/update pip & virtualenv
  become: yes
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - virtualenv
    - pip

- name: Manually create virtualenv
  command: virtualenv "{{ project_venv_path }}" -p python3
  args:
    creates: "{{ project_venv_path }}"

- name: Install dependencies
  become: yes
  pip: name={{ item }} state=latest executable=pip3 virtualenv={{ project_venv_path }}
  with_items:
    - django

- name: Download django-registation with git (sic!)
  become: yes
  git: dest=/tmp/django-registration repo=https://github.com/ubernostrum/django-registration.git

- name: Install django-registration
  become: yes
  command: "{{ project_venv_path }}/bin/python /tmp/django-registration/setup.py install"

