---
- name: Update cache
  become: yes
  apt: update_cache=true

- name: Install system packages
  become: yes
  apt: name="{{ item }}" state=present
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - ruby
    - tmux

- name: Install/update pip & virtualenv
  become: yes
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - virtualenv
    - pip

- name: Install django
  become: yes
  pip: name=django state=latest executable=pip3 virtualenv={{ project_venv_path }}

- name: Manually create virtualenv
  command: virtualenv "{{ project_venv_path }}" -p python3
  args:
    creates: "{{ project_venv_path }}"