---
- name: Install tmuxinator
  become: yes
  command: gem install tmuxinator

- name: mkdir tmuxinator directory
  file: path="~/.tmuxinator" state=directory

- name: symlink tmuxinator config
  template: src=tmuxinator.conf.jinja2 dest=~/.tmuxinator/twitter.yml

- name: Create run alias
  lineinfile:
    dest: ~/.bashrc
    regexp: alias run
    line: alias run="mux start twitter"

- name: Initialize dev DB
  command: chdir={{ project_path }} {{ project_venv_path }}/bin/initialize_twitter_db development.ini
